### ISSUE TITLE
Prefer Arrays over Objects

### ISSUE THREAD

**Issue by jason-earl** [aconchillo/guile-json#22]
guile-json currently prefers objects over arrays in certain circumstances. For example, this code:

`(scm->json '((1 2 3) (4 5 6)))`

returns:

`{"1":[2,3],"4":[5,6]}`

Sometimes I would prefer it to return something like this:

`[[1,2,3],[4,5,6]]`

I have a branch prefer_array that I used to test what I needed. I don't pretend to be any good at this, but it might be helpful to see what I mean.

**Comment by ZelphirKaltstahl** [comment]
I think the array representation is indeed closer to what it looks like in Guile and at least what I would expect to see when calling that procedure. :+1:

**Comment by aconchillo** [comment]
I think this makes sense and it's what I would also expect. I'm not sure how to solve this properly (without having to specify any extra parameter). I will ask the guile mailing lists for advice. Thanks!

**Comment by humanitiesNerd** [comment]
The module could store a default value in a parameter (in the sense of the parameters [described](https://www.gnu.org/software/guile/manual/html_node/Parameters.html) in the manual) so someone who wants to use `#:default 'array` as default can assign it once to the parameter

and the functions could read the parameter instead of expecting an additional argument

Maybe they could have an optional argument and that could supersede the value set in the parameter

So they could be called without the optional argument in the general case and return objects or arrays but in some specific cases they could be modified locally

Am I misunderstanding how parameters work ?

**Comment by aconchillo** [comment]
I think it would be better to not having to specify anything. I'm thinking on bringing back the (json) macro we had in version < 1.0. In you case you would do:

```
(json (array (1 2 3) (4 5 6)))
```

which returns:

```
((1 2 3) (4 5 6))
```

Still thinking about it.

**Comment by aconchillo** [comment]
And actually, removing the internal `alist` check, you only have to do this:

`(scm->json '((1 2 3) (4 5 6)))`

which returns:

`[[1,2,3],[4,5,6]]`

And you only need to use the `json` macro if you want to deal with objects. For example:

`(scm->json (json (object ("key1" "value1") ("key2" (1 2 3)))))`

returns

`{"key2":[1,2,3],"key1":"value1"}`

**Comment by aconchillo** [comment]
Please, take a look at the **Usage** examples on this branch https://github.com/aconchillo/guile-json/tree/reintroduce-syntax-macro

Let me know if this would work for you.

**Comment by rain-1** [comment]
The table here describes a bijective mapping between JSON and Guile (scheme expressions) https://github.com/aconchillo/guile-json#usage

For the implementation to translate lists like '((1 2 3) (4 5 6))) into an object rather than an array seems to violate this.

What is the reason for the JSON macro? If one wants to create an object they can provide a hash table rather than an assoc list.

I think deleting `((json-alist? scm) (json-build-object scm port escape pretty level))` was the correct fix. I would argue that bringing the JSON macro back is not needed and would recommend against it as it complicates the code and provides 2 different APIs to do the same thing.

**Comment by jason-earl** [comment]
The reintroduce-syntax-macro branch suits my needs perfectly.  Seriously, this has been so much fun.  I need to hack guile more often.  Thanks.

**Comment by aconchillo** [comment]
@rain-1 your comment makes total sense, thanks for the feedback. I will give that a try (not using the macro) and probably make a release soon.

**Comment by christopherlam** [comment]
@aconchillo mentioned on IRC - using hashmaps is elegant but it needs lots and lots of tests -- how would scheme's alists with duplicate keys be handled? Symbol/numeric/string/null/list keys? Do they survive a bidirectional transform? If not, they must at least be documented :smiley:

**Comment by aconchillo** [comment]
Hi @christopherlam ! This is who it would work (which is something already supported):

```
> (scm->json (alist->hash-table '((project . (1 2 3 4)) ("author" . bar))))
{"author":"bar","project":[1,2,3,4]}
```

or even

```
> (scm->json (alist->hash-table `((project . (1 2 3 4)) (author . ,(alist->hash-table '((foo . bar)))))))
{"author":{"foo":"bar"},"project":[1,2,3,4]}
```

To answer your questions:

The duplicates are handled by `alist->hash-table`, for example:

```
> (scm->json (alist->hash-table '((project . (1 2 3 4)) (author . bar) (author . foo))))
{"author":"bar","project":[1,2,3,4]}
```

The symbols, strings, numbers and lists are handled properly as you can see. Nothings has changed there. And yes, it survives a bidirectional transform as it did before. Before, guile-json was already using a hash-table internally. What changes is something that is only user-facing.

So, the only breaking change will be that it will not be possible to use alists directly as there's no way to tell if that's an object and array or a combination of both.

The only drawback is that it's a little bit more code to write, but safer and consistent.

Please, let me know if there are any concerns. I will wait before cutting a release.

**Comment by ZelphirKaltstahl** [comment]
> @aconchillo mentioned on IRC - using hashmaps is elegant but it needs lots and lots of tests -- how would scheme's alists with duplicate keys be handled?

I think duplicate keys are not an issue, as they are not possible in a Javascript object and validators silently remove the duplicates.

> > (scm->json (alist->hash-table '((project . (1 2 3 4)) (author . bar) (author . foo))))
{"author":"bar","project":[1,2,3,4]}

This however is interesting, as I would have expected the last definition to be the one overwriting the first. But apparently there is some "does this key already exist?" check somewhere? So maybe the documentation should then contain information about which of the keys will be preserved.

**Comment by christopherlam** [comment]
> So, the only breaking change will be that it will not be possible to use alists directly as there's no way to tell if that's an object and array or a combination of both.
> 
> The only drawback is that it's a little bit more code to write, but safer and consistent.

I think this solution is elegant. 

However I'll need to change the propsed PR for Gnucash. My plan was to create a nested JSON chartjs options from the following default:
```
(define options 
 (list  (cons 'maintainAspectRatio #f)
        (cons 'chartArea (list
                          (cons 'backgroundColor "#fffdf6")))
        (cons 'legend (list
                       (cons 'position 'right)
                       (cons 'reverse #f)
                       (cons 'labels "x"))))
```
... then manipulate this nested-alist tree by diving into the appropriate sub-list, manipulate appropriate with `list-set!` etc, then finally running `(display (scm->json-string options #:pretty #t) port)` to create the nested JSON options tree as follows:

```
var chartjsoptions = 
{
    "type" : "bar",
    "options" : 
    {
        "maintainAspectRatio" : false,
        "chartArea" : 
        {
            "backgroundColor" : "#fffdf6"
        },
        "legend" : 
        {
            "position" : "right",
            "reverse" : false,
            "labels" : 
            {
                "fontColor" : "black"
            }
        }, (etc)
```
So, nested hash-tables will need to be used instead of nested alists.

**Comment by aconchillo** [comment]
Yes, you will need to to something like this:

```
(define options
   (alist->hash-table
     `((maintainAspectRatio . #f)
        (charArea . ,(alist->hash-table '((backgroundColor . "#fffdf6"))))
        (legend . ,(alist->hash-table '((position . right)
                                        (reverse . #f)
                                        (labels . "x")))))))
```

Then:

```
> (scm->json options #:pretty #t)
{
  "maintainAspectRatio" : false,
  "charArea" :
  {
    "backgroundColor" : "#fffdf6"
  },
  "legend" :
  {
    "reverse" : false,
    "position" : "right",
    "labels" : "x"
  }
}
```

Btw, you can send the output to a port directly:

`(scm->json options port #:pretty #t)`

For example:

`(scm->json options (current-output-port) #:pretty #t)`
