### ISSUE TITLE
array datatypes - how to create blank slots?

### ISSUE THREAD

**Issue by christopherlam** [aconchillo/guile-json#40]
I'm not sure if this is a genuine issue, or valid json. But I hope I can make sense.

In scheme I can create a blank vector with `(make-vector 3)` which creates `#(#unspecified #unspecified #unspecified)`. This vector is currently impossible to convert to json. Could this be convertible to `[,,]`?

In javascript I can create an array with empty slots: `a = [0,1,2,,,5]` whereby `a[3]` is `undefined`. Converting this to scm leads to `#(0 1 2 5)` which is imho not desirable. A good scm output would be `#(0 1 2 #unspecified #unspecified 5)`?

**Comment by aconchillo** [comment]
Hi @christopherlam . Sorry for the long delay. Please take a look at the PR above. I have fixed the issue you mentioned, however the *unspecified* type is it's own beast. See:

http://git.savannah.gnu.org/cgit/guile.git/tree/module/ice-9/boot-9.scm?h=stable-2.2#n3113

For example, consider this (which works):

```
scheme@(guile-user)> (use-modules (srfi srfi-43))
scheme@(guile-user)> (vector-for-each (lambda (i v) (display (unspecified? v))) (make-vector 3))
#t#t#t
```

but if we use a variable:

```
scheme@(guile-user)> (define v #(1 2 *unspecified* *unspecified* 5))
scheme@(guile-user)> (vector-for-each (lambda (i v) (display (unspecified? v))) v)
#f#f#f#f#f
```

I think the reason is because `*unspecified*` is considered a symbol when defining a vector. I don't know how to make it a real unspecified value.

One option would be to only support it when parsing, but not when building. That is, we just use the PR above.

**Comment by aconchillo** [comment]
In any case I'm not really sure about all this. `[0,1,2,,,5]` would not be valid JSON according to the spec, so I'm not sure it should be supported.  Which means this `(scm->json-string #(1 2 *unspecified* *unspecified* 5))` should throw an exception. It now does after #48 .

**Comment by christopherlam** [comment]
Hi, I can't remember the exact use case for above... it was for https://github.com/Gnucash/gnucash/blob/master/gnucash/report/html-chart.scm to convert scm data into json for chartjs. It was for adding data into scm nested alist eg `'((options . ...) (data . ((datasets . (data . #(10 20 30)) (label . "series"))))))` etc.

In any case I'd rather subscribe to @johnwcowan view on extreme adherence to standards rather than implementing a dialect-specific hack. So perhaps the issue should really be to properly document nonconvertible scm types, and a test suite to illustrate?

**Comment by aconchillo** [comment]
Thanks, I'll add a comment in the README and a test.
