### ISSUE TITLE
optional entries in json mapping

### ISSUE THREAD

**Issue by roptat** [aconchillo/guile-json#61]
Hi!

I'm using define-json-mapping to parse and serialize jrd records (for the webfinger protocol: https://tools.ietf.org/html/rfc7033#section-3.1). Here's my current code for the link record as an example:

```scheme
(define-json-mapping <link-record> make-link-record link-record?
  json->link-record <=> link-record->json
  (rel        link-record-rel) ; string
  (type       link-record-type) ; string
  (href       link-record-href) ; string
  (titles     link-record-titles) ; alist whose keys are languages or "und" and values are strings
  (properties link-record-properties)) ; alist whose keys and values are strings
```

nice and easy, `json->link-record` works as intended: unspecified fields get `#f`. Now, when I try to generate that back, as in:

```scheme
(link-record->json "http://openid.net/specs/connect/1.0/issuer" #f "https://openid.example.com" #f #f)
```

the result is not what I expect (I tried with `#nil` too):

```json
{ "rel": "http://openid.net/specs/connect/1.0/issuer",
  "type": false,
  "href": "https://openid.example.com",
  "titles": false,
  "propeties": false
}
```

But I expected "type", "titles" and "properties" to not be defined at all. So maybe guile-json could not cons the value when it's `#f` or `#nil` (but it's hard to distinguish from the case of an empty list or the literal false), or provide a way to specify a predicate under which to add the field or not.

Wdyt?

**Comment by aconchillo** [comment]
Hi! Thank you for reporting this. It's actually a very common and useful feature in other languages. For example, in Go you would use `omitempty` to not serialize a field if a value hasn't been assigned.

I have a branch where I have added support for this. Unspecified fields will now have the value `*unspecified*`. You mention that `json->link-record` would assign a `#f` but that's not actually correct, since a field could be a boolean in which case there would not be a way to identify it.

So, now you can do:

```
(link-record->json (make-link-record "http://openid.net/specs/connect/1.0/issuer" *unspecified* "https://openid.example.com" *unspecified* *unspecified*))
```

which will serialize to:

```
{"rel":"http://openid.net/specs/connect/1.0/issuer","href":"https://openid.example.com"}
```

If we parse this it will initialize non-existing fields to *unspecified*, which means we can now combine `link-record->json` and `json->link-record` without any issues.

```
(link-record->json (json->link-record (link-record->json (make-link-record "http://openid.net/specs/connect/1.0/issuer" *unspecified* "https://openid.example.com" *unspecified* *unspecified*))))
```

This is not merged into master, but you can find the needed changes here: https://github.com/aconchillo/guile-json/commit/959aec27a37c3ff231a8866fa1039b12f1cc85d2

Let me know if that would work for you. I'll sleep on it to see if there's something better.

**Comment by roptat** [comment]
Thank you! It works very well for my case.
